apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin-v1
    - httpbin-v2
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: httpbin-v1
            port:
              number: 8000
          weight: 80
        - destination:
            host: httpbin-v2
            port:
              number: 8000
          weight: 20
      timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx,reset,connect-failure
