apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: httpbin
      namespace: workload
  - apiVersion: v1
    kind: Service
    metadata:
      name: httpbin
      namespace: workload
      labels:
        app: httpbin
    spec:
      ports:
        - name: http
          port: 8000
          targetPort: 80
      selector:
        app: httpbin
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "5"
      name: httpbin
      namespace: workload
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: httpbin
          version: v1
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: httpbin
            version: v1
        spec:
          containers:
            - image: kennethreitz/httpbin
              imagePullPolicy: IfNotPresent
              name: httpbin
              ports:
                - containerPort: 80
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          serviceAccount: httpbin
          serviceAccountName: httpbin
          terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
