apiVersion: v1
kind: Namespace
metadata:
  name: workload-gitlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-deploy
  namespace: workload-gitlab
rules:
- apiGroups: ["", "apps", "batch", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-deploy
  namespace: workload-gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-runner-deploy
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: gitlab-runner
