apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: sleep
      namespace: workload
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app: sleep
        service: sleep
      name: sleep
      namespace: workload
    spec:
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: sleep
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
      name: sleep
      namespace: workload
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: sleep
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: sleep
        spec:
          containers:
            - command:
                - /bin/sleep
                - infinity
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              name: sleep
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/sleep/tls
                  name: secret-volume
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          serviceAccount: sleep
          serviceAccountName: sleep
          terminationGracePeriodSeconds: 0
          volumes:
            - name: secret-volume
              secret:
                defaultMode: 420
                optional: true
                secretName: sleep-secret
kind: List
metadata:
  resourceVersion: ""
